### ISSUE TITLE
Unable to Locate : Submit_Application_button

### ISSUE THREAD

**Issue by Master-Mind-007** [AmmeySaini/Edu-Mail-Generator#104]
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="submit-application-button"]"}

**Comment by FeelsBadMan1** [comment]
This Traceback should be obvious and easy to solve by your own. You now understand that it could not find the element with the given xpath that probably means that the xpath got changed by the site since the last update. You should open the bot again then wait for the error to be raised and on the Website you probably should see a submit button. rightclick on the button and press inspect elements. a devtool will open with some code that is higlighted so rightclick on the code => copy => copy xpath then paste the new xpath into the code
